-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.profiles
(
    id uuid NOT NULL,
    updated_at timestamp with time zone,
    username text COLLATE pg_catalog."default",
    avatar_url text COLLATE pg_catalog."default",
    website text COLLATE pg_catalog."default",
    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT profiles_username_key UNIQUE (username),
    CONSTRAINT profiles_id_fkey FOREIGN KEY (id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT username_length CHECK (char_length(username) >= 3)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.profiles
    OWNER to postgres;

GRANT ALL ON TABLE public.profiles TO anon;

GRANT ALL ON TABLE public.profiles TO authenticated;

GRANT ALL ON TABLE public.profiles TO postgres;

GRANT ALL ON TABLE public.profiles TO service_role;

CREATE TABLE IF NOT EXISTS public.pomodoros
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    starting_at time with time zone DEFAULT '09:00:00+02'::time with time zone,
    focus smallint DEFAULT '25'::smallint,
    break smallint DEFAULT '5'::smallint,
    long_break smallint DEFAULT '15'::smallint,
    active boolean DEFAULT true,
    loop_before_long_break smallint DEFAULT '4'::smallint,
    ending_at time with time zone DEFAULT '18:00:00+01'::time with time zone,
    CONSTRAINT pomodoros_pkey PRIMARY KEY (id),
    CONSTRAINT pomodoros_created_by_fkey FOREIGN KEY (created_by)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.pomodoros
    OWNER to postgres;

GRANT ALL ON TABLE public.pomodoros TO anon;

GRANT ALL ON TABLE public.pomodoros TO authenticated;

GRANT ALL ON TABLE public.pomodoros TO postgres;

GRANT ALL ON TABLE public.pomodoros TO service_role;
